name: Security Pipeline

on:
  push:
  pull_request:

jobs:
  horusec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Horusec CLI
        run: |
          curl -Ls https://github.com/ZupIT/horusec/releases/latest/download/horusec_linux_amd64 -o horusec
          chmod +x horusec
          sudo mv horusec /usr/local/bin/horusec

      - name: Run Horusec (SAST) without Docker
        run: horusec start -p . --output-format=json --json-output-file=horusec-report.json --disable-docker

      - name: Upload Horusec report artifact
        uses: actions/upload-artifact@v4
        with:
          name: horusec-report
          path: horusec-report.json

  zap_scan:
    runs-on: ubuntu-latest
    needs: horusec

    steps:
      - uses: actions/checkout@v3

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
