name: Security Pipeline

on: [push, pull_request]

jobs:
  horusec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Horusec
        run: |
          curl -Ls https://github.com/ZupIT/horusec/releases/latest/download/horusec_linux_amd64 -o horusec
          chmod +x horusec
          sudo mv horusec /usr/local/bin/horusec
      - name: Run Horusec
        run: horusec start -p . --output-format=json --json-output-file=horusec-report.json

  zap_scan:
    runs-on: ubuntu-latest
    needs: horusec
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
