name: Security Pipeline

on: [push, pull_request]

jobs:
  horusec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Horusec
        run: curl -fsSL https://horusec.io/bin/install.sh | bash
      - name: Run Horusec
        run: horusec start -p . --output-format=json -o horusec-report

  zap_scan:
    runs-on: ubuntu-latest
    needs: horusec
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'